import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../src/app/styles/globals.css";
import App from "@/app";
import { Layout } from "@/shared/ui/Layout/Layout";
import { Toast } from "@/shared/ui/Toast/ui/Toast";

if (
  process.env.NEXT_RUNTIME === "nodejs" &&
  process.env.NODE_ENV !== "production" &&
  process.env.NEXT_PUBLIC_MSW_ENABLED !== "false"
) {
  import("@/shared/config/mocks/server").then(({ server }) => {
    server.listen();
  });
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <App>
          <Layout>{children}</Layout>
          <Toast />
        </App>
      </body>
    </html>
  );
}
